/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author danib
 */
public class Base5 extends javax.swing.JPanel {

    /**
     * Creates new form Base5
     */
    public Base5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_base5 = new javax.swing.JPanel();
        lbl_base5 = new javax.swing.JLabel();
        lbl_base25 = new javax.swing.JLabel();
        lbl_base125 = new javax.swing.JLabel();
        lbl_base625 = new javax.swing.JLabel();
        jtf_base625 = new javax.swing.JTextField();
        jtf_base125 = new javax.swing.JTextField();
        jtf_base25 = new javax.swing.JTextField();
        jtf_base5 = new javax.swing.JTextField();

        pnl_base5.setBackground(new java.awt.Color(181, 131, 141));
        pnl_base5.setMaximumSize(new java.awt.Dimension(690, 460));
        pnl_base5.setMinimumSize(new java.awt.Dimension(690, 460));

        lbl_base5.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        lbl_base5.setText("Base 5: ");

        lbl_base25.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        lbl_base25.setText("Base 25: ");

        lbl_base125.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        lbl_base125.setText("Base 125: ");

        lbl_base625.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        lbl_base625.setText("Base 625: ");

        jtf_base625.setBackground(new java.awt.Color(229, 152, 155));
        jtf_base625.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N

        jtf_base125.setBackground(new java.awt.Color(229, 152, 155));
        jtf_base125.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N

        jtf_base25.setBackground(new java.awt.Color(229, 152, 155));
        jtf_base25.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N

        jtf_base5.setBackground(new java.awt.Color(229, 152, 155));
        jtf_base5.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N

        javax.swing.GroupLayout pnl_base5Layout = new javax.swing.GroupLayout(pnl_base5);
        pnl_base5.setLayout(pnl_base5Layout);
        pnl_base5Layout.setHorizontalGroup(
            pnl_base5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_base5Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(pnl_base5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(pnl_base5Layout.createSequentialGroup()
                        .addComponent(lbl_base625, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46)
                        .addComponent(jtf_base625, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(pnl_base5Layout.createSequentialGroup()
                        .addComponent(lbl_base125, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addComponent(jtf_base125, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(pnl_base5Layout.createSequentialGroup()
                        .addComponent(lbl_base25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addComponent(jtf_base25, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(pnl_base5Layout.createSequentialGroup()
                        .addComponent(lbl_base5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68)
                        .addComponent(jtf_base5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addGap(160, 160, 160))
        );
        pnl_base5Layout.setVerticalGroup(
            pnl_base5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_base5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pnl_base5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(pnl_base5Layout.createSequentialGroup()
                        .addComponent(lbl_base5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(76, 76, 76)
                        .addComponent(lbl_base25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(76, 76, 76)
                        .addComponent(lbl_base125, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(76, 76, 76)
                        .addComponent(lbl_base625, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_base5Layout.createSequentialGroup()
                        .addComponent(jtf_base5)
                        .addGap(70, 70, 70)
                        .addComponent(jtf_base25)
                        .addGap(70, 70, 70)
                        .addComponent(jtf_base125)
                        .addGap(70, 70, 70)
                        .addComponent(jtf_base625)))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_base5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_base5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField jtf_base125;
    public javax.swing.JTextField jtf_base25;
    public javax.swing.JTextField jtf_base5;
    public javax.swing.JTextField jtf_base625;
    private javax.swing.JLabel lbl_base125;
    private javax.swing.JLabel lbl_base25;
    private javax.swing.JLabel lbl_base5;
    private javax.swing.JLabel lbl_base625;
    private javax.swing.JPanel pnl_base5;
    // End of variables declaration//GEN-END:variables
}
